=== alvaroiniguezdisla/SISTEMAS_WEB_II/5_XML/Ejercicio_2_DTD/articles.dtd
<!ELEMENT articles (article+)>

<!ELEMENT article (name, month, author, reviews, feedback, reviews)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT author EMPTY>
<!ELEMENT reviews (#PCDATA)>
<!ELEMENT feedback (#PCDATA)>

<!ATTLIST article id CDATA #REQUIRED>
<!ATTLIST author name CDATA #REQUIRED>
<!ATTLIST reviews lang CDATA #REQUIRED>

=== alvaroiniguezdisla/SISTEMAS_WEB_II/5_XML/Ejercicio_2_DTD/articles.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE articles SYSTEM "articles.dtd">

<articles>
  <article id="x34675">
    <name>Apache Spark Architecture</name>
    <month>december</month>
    <author name="kay vennisla"/>
    <reviews lang=""/>
    <feedback> high rating</feedback>
    <reviews lang="de">The best content with diagrams</reviews>
  </article>
</articles>
